ShipOCereal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('about/', include('about.urls')),
    path('cart/', include('cart.urls')),
    path('', views.index, name='homeIndex'),
    path('user/', include('user.urls'))
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="cartIndex"),
    path('<int:id>', views.cartUpdate, name='cartItem'),
    path('payment', views.paymentIndex, name='payment'),
    path('contact', views.contactIndex, name='contact'),
    path('review', views.reviewOrder, name='reviewOrder')
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from django_countries.fields import CountryField

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, null=True, blank=True)
    device = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        if self.name:
            name = self.name
        else:
            name = self.device
        return str(name)


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    dateOrdered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=True)
    transactionId = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id) + " | " #+ str(self.customer.name)

    @property
    def getCartTotal(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def getCartItems(self):
        orderitems = self.orderitem_set.all()
        return orderitems

    @property
    def getNumItems(self):
        orderitems = self.orderitem_set.all()
        totalitems = sum([item.quantity for item in orderitems])
        return totalitems


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "order: " + str(self.order) + "| product: " + str(self.product.name)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total




class Payment(models.Model):
    class Month(models.IntegerChoices):
        JAN = 1, "01"
        FEB = 2, "02"
        MAR = 3, "03"
        APR = 4, "04"
        MAY = 5, "05"
        JUN = 6, "06"
        JUL = 7, "07"
        AUG = 8, "08"
        SEP = 9, "09"
        OCT = 10, "10"
        NOV = 11, "11"
        DES = 12, "12"

    class Year(models.IntegerChoices):
        TW1 = 21, "21"
        TW2 = 22, "22"
        TW3 = 23, "23"
        TW4 = 24, "24"
        TW5 = 25, "25"
        TW6 = 26, "26"
        TW7 = 27, "27"
        TW8 = 28, "28"
        TW9 = 29, "29"
        TH0 = 30, "30"



    user = models.OneToOneField(Customer, on_delete=models.CASCADE, unique=True)
    cardOwner = models.CharField(max_length=100, null=True)
    cardNumber = models.CharField(max_length=19, null=True)
    expirationDateMonth = models.PositiveSmallIntegerField(choices=Month.choices,
        default=Month.JAN)
    expirationDateYear = models.PositiveSmallIntegerField(choices=Year.choices,
        default=Year.TW2)
    cvc = models.CharField(max_length=3, null=True)


class Contact(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True)
    streetName = models.CharField(max_length=100, null=True)
    houseNumber = models.PositiveSmallIntegerField()
    city = models.CharField(max_length=100, null=True)
    country = CountryField()
    postalCode = models.PositiveBigIntegerField()

cart/forms/contactForm.py
from django.forms import ModelForm, widgets
from cart.models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'streetName', 'houseNumber', 'city', 'country', 'postalCode']
        exclude = ['id']
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'form_control', 'autocomplete': 'off', 'maxlength': 100}),
            'streetName': widgets.TextInput(attrs={'class': 'form_control', 'autocomplete': 'off', 'maxlength': 100}),
            'houseNumber': widgets.TextInput(attrs={'class': 'form_control', 'autocomplete': 'off', 'type': 'number'}),
            'city':widgets.TextInput(attrs={'class': 'form_control', 'autocomplete': 'off', 'maxlength': 100}),
            'country': widgets.Select(attrs={'class': 'form_control'}),
            'postalCode': widgets.TextInput(attrs={'class': 'form_control', 'autocomplete': 'off', 'type': 'number'})
        }

cart/forms/paymentForm.py
from django.forms import ModelForm, widgets
from cart.models import Payment


class PaymentForm(ModelForm):
    class Meta:
        model = Payment
        fields = ['cardOwner', 'cardNumber', 'expirationDateMonth', 'expirationDateYear', 'cvc']
        exclude = ['id']
        widgets = {
            'cardOwner': widgets.TextInput(attrs={'class': 'form_control', 'autocomplete': 'off', 'maxlength': 100}),
            'cardNumber': widgets.TextInput(attrs={'class': 'form_control', 'autocomplete': 'off', 'type':"tel", 'inputmode': "numeric", 'pattern':"[0-9\s]{13,19}", 'autocomplete':"cc-number", 'maxlength':"19", 'placeholder':"xxxx xxxx xxxx xxxx"}),
            'expirationDateMonth': widgets.Select(attrs={'class': 'form_control'}),
            'expirationDateYear':widgets.Select(attrs={'class': 'form_control'}),
            'cvc': widgets.TextInput(attrs={'class': 'form_control', 'autocomplete': 'off'}),
        }

cart/views.py
import datetime

from django.shortcuts import render, redirect
from .models import Customer, Order, Payment, OrderItem, Contact
from cart.forms.paymentForm import PaymentForm
from cart.forms.contactForm import ContactForm
from django_countries.fields import CountryField
import uuid
from datetime import datetime
# from user.forms.profile_form import ProfileForm, UserRegisterForm
# from user.models import Profile, SearchHistory

# Create your views here.
def index(request):
    order, created, customer = getOrder(request)

    context = {'order': order}
    return render(request, 'cart/index.html', context)

def cartUpdate(request, id):
    if 'quantity' in request.POST:
        newQuantity = int(request.POST['quantity'])
        if newQuantity <= 0:
            newQuantity = 1

        OrderItem.objects.filter(id=id).update(quantity=newQuantity)

    else:
        OrderItem.objects.filter(id=id).delete()

    return redirect('cartIndex')

def paymentIndex(request):
    month = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
    year = [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
    try:
        info = Payment.objects.get(user_id=request.user.customer.id)
    except:
        info = ''
    try:
        customer = request.user.customer
    except:
        device = request.COOKIES['device']
        if request.user.is_active:
            customer, created = Customer.objects.get_or_create(user=request.user, name=request.user.username)
        else:
            customer, created = Customer.objects.get_or_create(device=device)
    if request.method == 'POST':
        try:
            form = PaymentForm(request.POST)
            print(request.user)
            print(request.user.customer.id)
            pay = Payment.objects.get(user_id=request.user.customer.id)
            print(pay)
            print(pay.id)
            form.save(commit=False)
            myPayment = Payment(id=pay.id, user=request.user.customer, cardOwner=form.data['cardOwner'],
                                cardNumber=form.data['cardNumber'],
                                expirationDateMonth=form.data['expirationDateMonth'],
                                expirationDateYear=form.data['expirationDateYear'],
                                cvc=form.data['cvc'])
            myPayment.save(force_update=True)
            return redirect('reviewOrder')
        except:
            form = PaymentForm(request.POST)
            if form.is_valid():
                paymentform = form.save(commit=False)
                paymentform.user = customer
                paymentform.save()
                return redirect('reviewOrder')
    return render(request, 'cart/payment.html', {
        'form': PaymentForm(),
        'year': year,
        'month': month,
        'info': info
    })

def contactIndex(request):
    countryDict = {}
    for country in CountryField().countries:
        countryDict[country[0]] = country[1]
    try:
        info = Contact.objects.get(customer_id=request.user.customer.id)
    except:
        info = ''
    try:
        customer = request.user.customer
    except:
        device = request.COOKIES['device']
        if request.user.is_active:
            customer, created = Customer.objects.get_or_create(user=request.user, name=request.user.username)
        else:
            customer, created = Customer.objects.get_or_create(device=device)
    if request.method == 'POST':
        try:
            form = ContactForm(request.POST)
            print(request.user)
            print(request.user.customer.id)
            contact = Contact.objects.get(customer_id=request.user.customer.id)
            print(contact)
            print(contact.id)
            form.save(commit=False)
            myContact = Contact(id=contact.id,name=form.data['name'], streetName=form.data['streetName'],
                          houseNumber=form.data['houseNumber'], city=form.data['city'],
                          country=form.data['country'], postalCode=form.data['postalCode'],
                          customer_id=request.user.customer.id)
            myContact.save(force_update=True)
            return redirect('payment')
        except:
            form = ContactForm(request.POST)
            if form.is_valid():
                contactform = form.save(commit=False)
                contactform.customer = customer
                contactform.save()
                return redirect('payment')
    return render(request, 'cart/contact.html', {
        'form': ContactForm(),
        'info': info,
        'countryDict': countryDict
    })

def reviewOrder(request):

    order, created, customer = getOrder(request)

    contact = Contact.objects.filter(customer=customer).first()

    payment = Payment.objects.filter(user=customer).last()
    creditCard = ""
    try:
        creditstr = payment.cardNumber
        creditCard = creditstr[:4]
    except:
        creditCard = ""

    if request.method == 'POST':
        transId = str(uuid.uuid4())
        now = datetime.now()
        Order.objects.filter(customer=customer, complete=False).update(complete=True, transactionId=transId, dateOrdered=now)

        return render(request, 'cart/receipt.html', {
            'order': order,
            'transId': transId,
            'customer': request.user
        })


    return render(request, 'cart/review.html', {
        'order': order,
        'contact': contact,
        'payment': payment,
        'creditCard': creditCard
    })


# helper functions
def getOrder(request):
    try:
        customer = request.user.customer
    except:
        device = request.COOKIES['device']
        if request.user.is_active:
            customer, created = Customer.objects.get_or_create(user=request.user, name=request.user.username)
        else:
            customer, created = Customer.objects.get_or_create(device=device)

    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    return order, created, customer

templates/cart/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="limiter">
    <div class="container-login100 ">
<div class="wrap-login100">
<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'logoMakr-2rUmgb.png' %}" style="width:80%;" alt="IMG">
				</div>
    <form id="form" class="login100-form" method="post">
        {% csrf_token %}

        {{ info.country.attname }}
        <div class="login100-form">
            <h2 class="">Contact information</h2>
            <label for="id_name">Name:</label><input type="text" {% if  info != '' %}value="{{ info.name }}" {% endif %} name="name" class="form_control input100 mb-2" autocomplete="off" maxlength="100" required="" id="id_name">
            <label for="id_streetName">StreetName:</label><input type="text" {% if  info != '' %}value="{{ info.streetName }}" {% endif %} name="streetName" class="form_control input100 mb-2" autocomplete="off" maxlength="100" required="" id="id_streetName">
            <label for="id_houseNumber">HouseNumber:</label><input type="number" {% if  info != '' %}value="{{ info.houseNumber }}" {% endif %} name="houseNumber" class="form_control input100 mb-2" autocomplete="off" required="" id="id_houseNumber">
            <label for="id_city">City:</label><input type="text" {% if  info != '' %}value="{{ info.city }}" {% endif %} name="city" class="form_control input100 mb-2" autocomplete="off" maxlength="100" required="" id="id_city">
            <label for="id_country">Country:</label>
            <select name="country" class="form_control input100 mb-2" required="" id="id_country" style="width:17rem;">
            <option disabled selected >---------</option>
      {% for key, value in countryDict.items %}
                  <option value="{{ key }}"{% if key == info.country %} selected{% endif %}>{{ value }}</option>
           {% endfor %}


    </select>
    <label for="id_postalCode">PostalCode:</label><input type="number" {% if  info != '' %}value="{{ info.postalCode }}" {% endif %} name="postalCode" class="form_control input100 mb-2" autocomplete="off" required="" id="id_postalCode">



            <input type="submit" class="btn-btn-primary login100-form-btn mb-2" value="Continue" autocomplete="off" name="checkout"/>
            <a href="{% url "cartIndex" %}">
                <input type="button" class="btn  backButton" value="Back" name="back"/>
            </a>
        </div>
    </form>
    </div>
    </div>

    </form>
 </div>
{% endblock %}

templates/cart/index.html
 {% extends "base.html" %}
{% block content %}
<div class="container">
   <div class="card shopping-cart">
            <div id="cartHeader" class="card-header text-light">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                Shopping cart

                <div class="clearfix"></div>
            </div>
            <div class="card-body">
        {% for item in order.getCartItems %}
            <div class="cartItems" >
                {% include 'cart/singleRowItem.html' with item=item %}
            </div>
            {% endfor %}
                <div class="pull-right">
                    <a href="" class="btn btn-outline-secondary pull-right">
                        Update shopping cart
                    </a>
                    <a href="{% url 'productsIndex' %}"><input type="button" class="btn  backButton" value="Continue Shopping" name="continueShopping" id="shopback"></a>
                </div>
            </div>
            <div class="card-footer">
                <div class="pull-right" style="margin: 10px">
                    <a href="{% url 'contact' %}" class="btn btn-success pull-right">Checkout</a>
                    <div class="pull-right" style="margin: 5px">
                        Total price: <b>{{ order.getCartTotal }}</b>
                    </div>
                </div>
            </div>
        </div>
</div>
{% endblock %}

templates/cart/payment.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <div class="limiter">
    <div class="container-login100 ">
    <div class="wrap-login100">
<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'logoMakr-2rUmgb.png' %}" style="width:80%;" alt="IMG">
				</div>
    <form class="form form-horizontal login100-form" method="post">

        {% csrf_token %}



        <div class="login100-form ">
            <h2 class="">Payment Information</h2>
            <label for="id_cardOwner">CardOwner:</label>
            <input type="text" name="cardOwner" {% if  info != '' %}value="{{ info.cardOwner }}" {% endif %}class="form_control input100 mb-2" autocomplete="off" maxlength="100" required="" id="id_cardOwner">
            <label for="id_cardNumber">CardNumber:</label>
            <input type="tel" name="cardNumber" {% if  info != '' %}value="{{ info.cardNumber }}" {% endif %} class="form_control input100 mb-2" autocomplete="off" inputmode="numeric" pattern="[0-9\s]{16,19}" autocomplete="cc-number" maxlength="19" placeholder="XXXX XXXX XXXX XXXX" required="" id="id_cardNumber">
            <label for="id_expirationDateMonth">ExpirationDateMonth:</label>
            <select name="expirationDateMonth"  class="form_control input100 mb-2" id="id_expirationDateMonth">
                {% for i in month %}
                    <option value="{{ forloop.counter }}"{% if  info != '' %}{% if forloop.counter == info.expirationDateMonth %} selected {% endif %} {% endif %}>{{ i }}</option>
                {% endfor %}
            </select>

            <label for="id_expirationDateYear">ExpirationDateYear:</label>
            <select name="expirationDateYear" class="form_control input100 mb-2" id="id_expirationDateYear">
                {% for i in year %}
                    <option value="{{ i }}"{% if  info != '' %}{% if i == info.expirationDateYear %} selected {% endif %} {% endif %}>{{ i }}</option>
                {% endfor %}

            </select>
            <label for="id_cvc">Cvc:</label>
            <input type="tel" name="cvc" {% if  info != '' %}value="{{ info.cvc }}" {% endif %} class="form_control input100 mb-2" autocomplete="off" inputmode="numeric" pattern="[0-9\s]{3,3}" autocomplete="cvc" maxlength="3" placeholder="XXX" required="" id="id_cvc">
            <input name="chrome-autofill-dummy1" style='display:none' disabled/>
            <input name="chrome-autofill-dummy2" style='display:none' disabled/>




            <input type="submit" class="btn-btn-primary login100-form-btn mb-2 paymentButton" value="Confirm" autocomplete="off" />
            <a href="{% url "contact" %}">
                <input type="button" class="btn  backButton" value="Back" name="back"/>
            </a>

        </div>
    </form>
    </div>
    </div>
    </div>


{% endblock %}

templates/cart/receipt.html
{% extends 'base.html' %}
{% block content %}

        <div class="receipt">
            <div>
                <div class="headReceipt">
                    <h1>Thank You for your order!</h1>
                </div>
                <div class="receiptContent">
                    <h2>Confirmation email has been sent to: {{ customer.email }}</h2>
                    <h4>Order ID: {{ order.id }}</h4>
                    <h4>Transaction ID: {{ transId }}</h4>
                    <h4>Date: {{ order.dateOrdered }}</h4>
                </div>

            </div>
        </div>
{% endblock %}

templates/cart/review.html
{% extends 'base.html' %}
{% block content %}
    <div class="reviewContainer">
    <div id="reviewHeader">
        <h2 id="reviewh2">Review Order</h2>
    </div>
    <div class="custInfoContainer">
        <div class="customerInfo">
            <div class="infoHeader">
                <h4>shipping/billing address</h4>
            </div>
            <div class="infoContent">
                <p><b>name:</b> {{ contact.name }}</p>
                <p><b>streetname:</b> {{ contact.streetName }}</p>
                <p><b>house number:</b> {{ contact.houseNumber }}</p>
                <p><b>city:</b> {{ contact.city }}</p>
                <p><b>country:</b> {{ contact.country }}</p>
                <p><b>Postal code:</b> {{ contact.postalCode }}</p>
            </div>
            <a class="InfoUpdate" href="{% url 'contact' %}">
                <input class="changeButton" type="button" value="Update">
            </a>
        </div>

        <div class="customerInfo">
            <div class="infoHeader">
                <h4>Payment method</h4>
            </div>
            <div class="infoContent">
                <p><b>Card owner:</b> {{ payment.cardOwner }}</p>
                <p><b>Card Number ending with:</b> {{ creditCard }}</p>
                <p><b>expiration Month:</b> {{ payment.expirationDateMonth }}</p>
                <p><b>Expiration Year:</b> {{ payment.expirationDateYear }}</p>
                <p><b>cvc:</b> *** </p>
            </div>
            <a class="InfoUpdate" href="{% url 'payment' %}">
                <input class="changeButton" type="button" value="Change">
            </a>
        </div>
    </div>


        <div class="orderCart">
            <div class="infoHeader">
                <h4>Order Items</h4>
            </div>
            <div class="infoContent">
                {% for item in order.getCartItems %}
                    <div class="cartItems shadow">
                        {% include 'cart/singleItemReview.html' with item=item %}
                    </div>
                {% endfor %}
            </div>
        </div>
    <div id="confirmOrderBox" class="customerInfo">
            <div class="infoHeader">
                <h4>Order</h4>
            </div>
            <div class="infoContent">
                <p><b>Order Total:</b> {{ order.getCartTotal }} Kr</p>
                <p><b>Items in order:</b> {{ order.getNumItems }} pc(s)</p>
            </div>
            <a class="InfoUpdate" href="#">
                <form method="post">
                    {% csrf_token %}
                    <input class="confirmButton" type="submit"{% if order.getNumItems == 0 %} disabled {% endif %}{% if payment == None %} disabled {% endif %} {% if contact == None %} disabled {% endif %} value="Confirm Order">
                </form>
            </a>
        </div>
    </div>

{% endblock %}

templates/cart/reviewCart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/cart/singleItemReview.html
<div class="ItemRow">
    <div class="rowItem">
        <p>{{ item.quantity }}</p>
    </div>
    <div class="rowItem">
        <img class="reviewImg" src="{{ item.product.image }}" alt="product image">
    </div>
    <div class="rowItem">
        <p>{{ item.product.name }}</p>
    </div>

</div>

templates/cart/singleRowItem.html
                    <div class="row">
                        <div class="col-12 col-sm-12 col-md-2 text-center">
                                <img class="img-fluid" src="{{ item.product.image }}" alt="prewiew" width="120" height="80">
                        </div>
                        <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                            <h4 class="product-name"><strong>{{ item.product.name }}</strong></h4>
                            <h4>
                                <small>{{ item.product.description }}</small>
                            </h4>
                        </div>
                        <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                            <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                                <h6><strong>{{ item.product.price }} <span class="text-muted">x</span></strong></h6>
                            </div>
                            <div class="col-4 col-sm-4 col-md-4">
                                <div class="quantity">
                                    <form method="post" action="{% url 'cartItem' item.id %}">
                                    {% csrf_token %}

                                    <input type="number" step="1" max="99" min="1" value="{{ item.quantity }}" title="Qty" class="qty"
                                           size="4" name="quantity">
                                        <input type="submit" value="✓" class="plus quantPlus" name="quantityIncrease">
                                        </form>
                                </div>
                            </div>
                            <div class="col-2 col-sm-2 col-md-2 text-right">
                                <form method="post" action="{% url 'cartItem' item.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-xs" name="removeItem">
                                    <i class="fa fa-trash" aria-hidden="true">x</i>
                                </button>
                                    </form>
                            </div>
                        </div>
                    </div>
                    <hr>