ShipOCereal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('about/', include('about.urls')),
    path('cart/', include('cart.urls')),
    path('', views.index, name='homeIndex'),
    path('user/', include('user.urls'))
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="cartIndex"),
    path('<int:id>', views.cartUpdate, name='cartItem'),
    path('payment', views.paymentIndex, name='payment'),
    path('contact', views.contactIndex, name='contact'),
    path('review', views.reviewOrder, name='reviewOrder')
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register, name='register'),
    #path('login', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('login', views.loginIn, name='login'),
    path('logout', LogoutView.as_view(next_page='login'), name='logout'),
    path('profile', views.profile, name='profile'),
    path('history', views.history, name='history'),
    path('payment', views.payment, name='payment12'),
    path('names', views.names, name='names')
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from django_countries.fields import CountryField

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, null=True, blank=True)
    device = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        if self.name:
            name = self.name
        else:
            name = self.device
        return str(name)


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    dateOrdered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=True)
    transactionId = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id) + " | " #+ str(self.customer.name)

    @property
    def getCartTotal(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def getCartItems(self):
        orderitems = self.orderitem_set.all()
        return orderitems

    @property
    def getNumItems(self):
        orderitems = self.orderitem_set.all()
        totalitems = sum([item.quantity for item in orderitems])
        return totalitems


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "order: " + str(self.order) + "| product: " + str(self.product.name)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total




class Payment(models.Model):
    class Month(models.IntegerChoices):
        JAN = 1, "01"
        FEB = 2, "02"
        MAR = 3, "03"
        APR = 4, "04"
        MAY = 5, "05"
        JUN = 6, "06"
        JUL = 7, "07"
        AUG = 8, "08"
        SEP = 9, "09"
        OCT = 10, "10"
        NOV = 11, "11"
        DES = 12, "12"

    class Year(models.IntegerChoices):
        TW1 = 21, "21"
        TW2 = 22, "22"
        TW3 = 23, "23"
        TW4 = 24, "24"
        TW5 = 25, "25"
        TW6 = 26, "26"
        TW7 = 27, "27"
        TW8 = 28, "28"
        TW9 = 29, "29"
        TH0 = 30, "30"



    user = models.OneToOneField(Customer, on_delete=models.CASCADE, unique=True)
    cardOwner = models.CharField(max_length=100, null=True)
    cardNumber = models.CharField(max_length=19, null=True)
    expirationDateMonth = models.PositiveSmallIntegerField(choices=Month.choices,
        default=Month.JAN)
    expirationDateYear = models.PositiveSmallIntegerField(choices=Year.choices,
        default=Year.TW2)
    cvc = models.CharField(max_length=3, null=True)


class Contact(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True)
    streetName = models.CharField(max_length=100, null=True)
    houseNumber = models.PositiveSmallIntegerField()
    city = models.CharField(max_length=100, null=True)
    country = CountryField()
    postalCode = models.PositiveBigIntegerField()

user/models.py
from django.db import models
from  django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profileImage = models.CharField(max_length=9999)
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)



class SearchHistory(models.Model):
    url = models.URLField()
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

user/forms/profile_form.py
from django.forms import ModelForm, widgets
from user.models import Profile
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['id', 'user']
        widgets = {
            'profile_image': widgets.TextInput(attrs={'class': 'form_control'})
        }


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name','email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

user/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from user.forms.profile_form import ProfileForm, UserRegisterForm
from user.models import Profile, SearchHistory
from cart.forms.paymentForm import PaymentForm
from cart.models import Customer, Payment
from products.models import Product
from django.http import JsonResponse
# Create your views here.


def register(request):
    if request.method != 'POST':
        return render(request, 'user/register.html', {
            'form': UserRegisterForm()
        })
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            task = form.save()
            user = Profile()
            user.user = User.objects.get(id=task.id)
            user.profileImage = 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/user.png'
            user.firstName = form.cleaned_data['first_name']
            user.lastName = form.cleaned_data['last_name']
            user.save()
            return redirect('login')
    return render(request, 'user/register.html',{
        'form': UserRegisterForm()
    })


def profile(request):
    # Edit profile
    profile = Profile.objects.filter(user=request.user).first()
    if request.method == 'POST':
        form = ProfileForm(instance=profile, data=request.POST)

        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            user = Profile.objects.get(user=request.user.id)
            user = user.user
            user.first_name = request.POST['firstName']
            user.last_name = request.POST['lastName']
            user.save()
            return redirect('profile')
    return render(request, 'user/profile.html', {
        'form': ProfileForm(instance=profile),
        'profile': profile
    })


def history(request):
    idList = []
    newDict = {}
    for x in SearchHistory.objects.filter(user_id=request.user.id).order_by('-time')[:10]:
        y = x.time
        x = x.url
        x = x.split('/')
        x = x[-1]
        idList.append(int(x))
        newDict[Product.objects.filter(id=x)] = y
        # newList.append(y)
    print(newDict)
    context = {'SearchHistory': SearchHistory.objects.filter(user_id=request.user.id).order_by('-time')[:10],
               'products': newDict
               }
    return render(request, 'user/history.html', context)

def loginIn(request):
    if request.method == 'GET':
        return render(request, 'user/login.html')
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('homeIndex')
        else:
            return render(request, 'user/login.html')



def payment(request):
    month = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
    year = [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
    try:
        info = Payment.objects.get(user_id=request.user.customer.id)
    except:
        info = ''
    try:
        customer = request.user.customer
    except:
        device = request.COOKIES['device']
        if request.user.is_active:
            customer, created = Customer.objects.get_or_create(user=request.user, name=request.user.username)
        else:
            customer, created = Customer.objects.get_or_create(device=device)
    if request.method == 'POST':
        try:
            form = PaymentForm(request.POST)
            print(request.user)
            print(request.user.customer.id)
            pay = Payment.objects.get(user_id=request.user.customer.id)
            print(pay)
            print(pay.id)
            form.save(commit=False)
            myPayment = Payment(id=pay.id, user=request.user.customer, cardOwner=form.data['cardOwner'],
                                cardNumber=form.data['cardNumber'],
                                expirationDateMonth=form.data['expirationDateMonth'],
                                expirationDateYear=form.data['expirationDateYear'],
                                cvc=form.data['cvc'])
            myPayment.save(force_update=True)
            return redirect('payment12')
        except:
            form = PaymentForm(request.POST)
            if form.is_valid():
                paymentform = form.save(commit=False)
                paymentform.user = customer
                paymentform.save()
                return render(request, 'cart/index.html')
    return render(request, 'user/payment12.html', {
        'form': PaymentForm(),
        'year': year,
        'month': month,
        'info': info
    })

def names(request):
    username = list(User.objects.all().values('username'))
    return JsonResponse({'data': username})

templates/user/history.html
{% extends 'base.html' %}
{% block content %}
    <div class="historyContainer">
    <h1 class="p-2">Search History</h1>
        <div class="SH shadow">
        {% for key, value in products.items %}
            {% for product in key %}
                    {% include 'products/singleProduct.html' with item=product %}
                {% endfor %}
            <p class="shadow p-2">At time: {{ value }}</p>
        {% endfor %}
        </div>
        </div>

{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'logoMakr-2rUmgb.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="post">
                    {%  csrf_token %}
					<span class="">
                        <h3>Member Login</h3>
					</span>
                    {{ form }}
					<div class="wrap-input100">
						<input class="input100" type="text" name="username" placeholder="Username">
					</div>

					<div class="wrap-input100">
						<input class="input100" type="password" name="password" placeholder="Password">

						</span>
					</div>

					<div class="container">
                        <input class="login100-form-btn" type="submit">
					</div>


					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'register' %}">
							Create your Account
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>


{% endblock %}

templates/user/payment12.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <div class="limiter">
    <div class="container-login100 ">
    <div class="wrap-login100">
<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'logoMakr-2rUmgb.png' %}" style="width:80%;" alt="IMG">
				</div>
    <form class="form form-horizontal login100-form" method="post">
        {% csrf_token %}



        <div class="login100-form">

            <h2 class="">Payment Information</h2>
            <label for="id_cardOwner">CardOwner:</label>
            <input type="text" name="cardOwner" {% if  info != '' %}value="{{ info.cardOwner }}" {% endif %}class="form_control input100 mb-2" autocomplete="off" maxlength="100" required="" id="id_cardOwner">
            <label for="id_cardNumber">CardNumber:</label>
            <input type="tel" name="cardNumber" {% if  info != '' %}value="{{ info.cardNumber }}" {% endif %} class="form_control input100 mb-2" autocomplete="off" inputmode="numeric" pattern="[0-9\s]{16,19}" autocomplete="cc-number" maxlength="19" placeholder="XXXX XXXX XXXX XXXX" required="" id="id_cardNumber">
            <label for="id_expirationDateMonth">ExpirationDateMonth:</label>
            <select name="expirationDateMonth"  class="form_control input100 mb-2" id="id_expirationDateMonth">
                {% for i in month %}
                    <option value="{{ forloop.counter }}"{% if  info != '' %}{% if forloop.counter == info.expirationDateMonth %} selected {% endif %} {% endif %}>{{ i }}</option>
                {% endfor %}
            </select>

            <label for="id_expirationDateYear">ExpirationDateYear:</label>
            <select name="expirationDateYear" class="form_control input100 mb-2" id="id_expirationDateYear">
                {% for i in year %}
                    <option value="{{ i }}"{% if  info != '' %}{% if i == info.expirationDateYear %} selected {% endif %} {% endif %}>{{ i }}</option>
                {% endfor %}

            </select>
            <label for="id_cvc">Cvc:</label>
            <input type="tel" name="cvc" {% if  info != '' %}value="{{ info.cvc }}" {% endif %} class="form_control input100 mb-2" autocomplete="off" inputmode="numeric" pattern="[0-9\s]{3,3}" autocomplete="cvc" maxlength="3" placeholder="XXX" required="" id="id_cvc">
            <input name="chrome-autofill-dummy1" style='display:none' disabled/>
            <input name="chrome-autofill-dummy2" style='display:none' disabled/>




            <input type="submit" class="btn-btn-primary login100-form-btn mb-2" value="Confirm" autocomplete="off" />
        </div>
    </form>
    </div>
    </div>
    </div>


{% endblock %}

templates/user/profile.html
{% extends 'base.html' %}
{% block content %}
        {% load static %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'logoMakr-2rUmgb.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form mt-0" method="post">
                    {%  csrf_token %}
					<span class="">
                        <h3>Edit Profile</h3>
					</span>
                    <div class="wrap-input100">
                        {%  csrf_token %}
                        Profile image
                        <img src="{{ user.profile.profileImage }}" class="rounded-circle z-depth-0"
            alt="avatar image" height="50" width="50" >
                        <input type="text" class="input100 mt-2" name="profileImage" value="{{ profile.profileImage }}" maxlength="9999" required="" id="id_profileImage">
                        First name
                        <input type="text" class="input100" name="firstName" value="{{ profile.firstName }}" maxlength="100" required="" id="id_firstName">
                        Last name
                        <input type="text" class="input100" name="lastName" value="{{ profile.lastName }}" maxlength="100" required="" id="id_lastName">
                    </div>


					<div class="container">
                        {%  csrf_token %}
                        <button id="profileUpdate" class="login100-form-btn" type="Update" value="update">Confirm</botton>
					</div>


				</form>
			</div>
		</div>
	</div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'logoMakr-2rUmgb.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="post">
                    {%  csrf_token %}
					<span class="login100-form-title">
						Create an account
					</span>

					<div class="wrap-input100">
                        <h6>Username</h6>
						<input id="usernameInput" class="input100" type="text" name="username">
                        <input id="checkUsername" type="button" value="check availibility">
                        <div id="userName">

                        </div>
					</div>

					<div class="wrap-input100">
                        <h6>First name</h6>
						<input class="input100" type="text" name="first_name">
					</div>

                    <div class="wrap-input100">
                        <h6>Last name</h6>
						<input class="input100" type="text" name="last_name">
					</div>

                    <div class="wrap-input100">
                        <h6>Email</h6>
						<input class="input100" type="email" name="email">
					</div>

                    <div class="wrap-input100">
                        <h6>Password</h6>
						<input class="input100" type="password" name="password1">
					</div>

                    <div class="wrap-input100">
                        <h6>Confirm password</h6>
						<input class="input100" type="password" name="password2">
					</div>

					<div class="container-login100-form-btn">
						<input class="login100-form-btn" type="submit" value="Register">
					</div>
                    <div class="text-center p-t-136">
						<a class="txt2" href="{% url 'login' %}">
							Already Have An Account? Sign in
						</a>



					</div>
				</form>
			</div>
		</div>
	</div>

{% endblock %}